### ISSUE TITLE
How to get raw data in realtime instead of graphical representation 

### ISSUE THREAD

**Issue by bharambetejas** [wgolab/WatCA#2]

**Comment by wgolab** [comment]
The raw data is beamed in realtime from YCSBConnectorWrapper to RealtimeMain.Handler.  You can intercept the data in RealtimeMain.Handler, or you can replace RealtimeMain entirely with a program that captures data from the appropriate port.  Also please note that if you run RealtimeMain with the "saveLogs" command line option, a log file will be saved in the local file system each time you execute a workload.

**Comment by bharambetejas** [comment]
Thank You for this. But I am not able to execute run_watca.sh file as well. Following is what I get.
![error](https://user-images.githubusercontent.com/17508216/52427076-4113f500-2acd-11e9-87a4-6e599816dd49.png)
This is the content of my settings file.
![screenshot from 2019-02-07 11 42 31](https://user-images.githubusercontent.com/17508216/52427225-8df7cb80-2acd-11e9-84ff-cc794d25b3a0.png)

I have created one ec2 ubuntu instance and one host ubuntu. I have cloned watca and followed the instructions. I have ran setup_ubuntu.sh on both the above machines.

**Comment by wgolab** [comment]
You have to build the code first using maven.  I pushed in an updated run_watca.sh script that will do that for you automatically.

**Comment by bharambetejas** [comment]
That worked, however i encountered a problem where permission is denied while connecting to the server. Do I need to include my aws key .pem file in the realtime folder as well.
![screenshot from 2019-02-07 14 28 35](https://user-images.githubusercontent.com/17508216/52437433-e8e8ed00-2ae4-11e9-9175-0702997fb1c3.png)

**Comment by wgolab** [comment]
Please verify first that you can SSH into all the ec2 instances using passwordless authentication.

**Comment by bharambetejas** [comment]
That worked. Thank You. 
I am still having problem when I start Noaql from WatCA gui its showing /cassandra/current-version: no such file or directory.
And the graphs are not displaying anything.
I would like your help in what format are the log files generated?.
I really appreciate your help on this

**Comment by wgolab** [comment]
This means Cassandra was not installed properly.  Did the setup_ubuntu.sh script run successfully?

**Comment by bharambetejas** [comment]
it showed that current-version no such file or directory while running setup_ubuntu.sh script. Is there any solution to this?

**Comment by wgolab** [comment]
It is possible that the setup script failed because SSH was not configured properly.  It is also possible that the script is outdated.  Can you run it again and share some output?  Also provide details on the VM type.

**Comment by bharambetejas** [comment]
![screenshot from 2019-02-12 16-19-59](https://user-images.githubusercontent.com/17508216/52668644-14534980-2ee2-11e9-8fab-ba95dc959905.png)

This is the output I get when I run setup_ubuntu.sh script. In this script the CVER is 2.2.7, but its the same even if I update ucsn and cassandra to latest version.
my ec2 machine is ubuntu 14.04. I am running just one instance.I run setup_ubuntu.sh script on both the instance and the local machine.

**Comment by bharambetejas** [comment]
Is it possible to post or a demonstration video of WatCA realtime setup, maybe I am messing up somewhere in the setup

**Comment by wgolab** [comment]
It looks like the setup script ran fine.  The unlink warning is benign.

**Comment by bharambetejas** [comment]
Is there any video demonstration or tutorial that I can follow?
